version: '3.1'

services:
  postgresql:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: 1111
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - 5433:5433
