# Generated by Django 4.0.1 on 2022-01-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_out', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Расход')),
                ('categories', models.CharField(choices=[('av', 'Автомобиль'), ('dm', 'Дом'), ('zd', 'Здоровье'), ('ls', 'Личные расходы'), ('od', 'Одежда'), ('pt', 'Питание'), ('pd', 'Подарки'), ('sr', 'Семейные расходы'), ('tx', 'Техника'), ('us', 'Услуги')], default='ls', max_length=3, verbose_name='Категория')),
                ('comment', models.CharField(blank=True, max_length=130, verbose_name='Комментарий')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_income', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Доход')),
                ('categories', models.CharField(choices=[('zp', 'Зарплата'), ('bs', 'Бизнес'), ('dr', 'Другое')], default='dr', max_length=3, verbose_name='Категория')),
                ('comment', models.CharField(blank=True, max_length=130, verbose_name='Комментарий')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
        ),
    ]
