# Generated by Django 4.0.1 on 2022-01-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='cash_out',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Расход'),
        ),
        migrations.AlterField(
            model_name='income',
            name='cash_income',
            field=models.DecimalField(decimal_places=2, help_text='Формат: хх.хх', max_digits=50, verbose_name='Доход'),
        ),
    ]
